# Generated by Django 2.2 on 2021-07-17 15:19

import app_shops.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('img', models.ImageField(default='../static/img/app_shops/tshirt.png', upload_to=app_shops.models.get_upload_path_photo)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price')),
                ('amount', models.IntegerField(default=1, verbose_name='amount')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.Shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='DiscountShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_percentage', models.BooleanField(default=True, verbose_name='is percentage')),
                ('percentage', models.IntegerField(default=0, verbose_name='percentage')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='money')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.Shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'discount shop',
                'verbose_name_plural': 'discounts shops',
            },
        ),
        migrations.CreateModel(
            name='DiscountGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_percentage', models.BooleanField(default=True, verbose_name='is percentage')),
                ('percentage', models.IntegerField(default=0, verbose_name='percentage')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='money')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.Goods', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'discount good',
                'verbose_name_plural': 'discounts goods',
            },
        ),
    ]
