# Generated by Django 2.2 on 2021-07-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountgoods',
            name='money',
            field=models.IntegerField(default=0, verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='discountshop',
            name='money',
            field=models.IntegerField(default=0, verbose_name='money'),
        ),
    ]
