# Generated by Django 2.2 on 2021-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_auto_20210728_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountgoods',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='discountshop',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price'),
        ),
    ]
