# Generated by Django 2.2 on 2021-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_auto_20210728_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountgoods',
            name='percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='percentage'),
        ),
        migrations.AlterField(
            model_name='discountshop',
            name='percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='percentage'),
        ),
    ]
