# Generated by Django 2.2 on 2021-07-17 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=1500, verbose_name='about')),
                ('money_in_account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='money in account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.Goods', verbose_name='goods')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'shopping history',
                'verbose_name_plural': 'shopping history',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.Goods', verbose_name='goods')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Profile', verbose_name='profile')),
            ],
        ),
    ]
