# Generated by Django 2.2 on 2021-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='amount'),
        ),
    ]
