# Generated by Django 2.2 on 2021-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_shoppinghistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_spent_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='amount spent money'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money_in_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='money in account'),
        ),
    ]
